#include "StarshipSimulator/render/texture.h"

#include <algorithm>
#include <bit>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <format>
#include <limits>
#include <span>
#include <stdexcept>

#include <SDL3/SDL_error.h>
#include <SDL3/SDL_gpu.h>

#include "StarshipSimulator/render/GpuHandle.h"

namespace StarshipSimulator
{

GpuTexture createTexture(SDL_GPUDevice* device, const TextureData& data)
{
    if (data.width == 0 || data.height == 0 || data.pixels.empty() ||
        data.pixels.size() > std::numeric_limits<std::uint32_t>::max())
    {
        throw std::runtime_error(std::format("Cannot create a {}x{} texture from {} bytes",
                                             data.width, data.height, data.pixels.size()));
    }
    const std::uint32_t levels =
        data.mipmaps ? static_cast<std::uint32_t>(std::bit_width(std::max(data.width, data.height)))
                     : 1U;
    SDL_GPUTextureUsageFlags usage = SDL_GPU_TEXTUREUSAGE_SAMPLER;
    if (levels > 1)
    {
        usage |= SDL_GPU_TEXTUREUSAGE_COLOR_TARGET;  // mipmaps are generated by blitting
    }
    const SDL_GPUTextureCreateInfo info{
        .type                 = SDL_GPU_TEXTURETYPE_2D,
        .format               = data.format,
        .usage                = usage,
        .width                = data.width,
        .height               = data.height,
        .layer_count_or_depth = 1,
        .num_levels           = levels,
        .sample_count         = SDL_GPU_SAMPLECOUNT_1,
    };
    const auto                            size = static_cast<std::uint32_t>(data.pixels.size());
    const SDL_GPUTransferBufferCreateInfo transferInfo{
        .usage = SDL_GPU_TRANSFERBUFFERUSAGE_UPLOAD, .size = size, .props = 0};
    GpuTexture              texture(device, SDL_CreateGPUTexture(device, &info));
    const GpuTransferBuffer transfer(device, SDL_CreateGPUTransferBuffer(device, &transferInfo));
    if (!texture.valid() || !transfer.valid())
    {
        throw std::runtime_error(std::format("Cannot create a {}x{} texture: {}", data.width,
                                             data.height, SDL_GetError()));
    }
    void* mapped = SDL_MapGPUTransferBuffer(device, transfer.get(), false);
    if (mapped == nullptr)
    {
        throw std::runtime_error(std::format("Cannot map a transfer buffer: {}", SDL_GetError()));
    }
    std::memcpy(mapped, data.pixels.data(), data.pixels.size());
    SDL_UnmapGPUTransferBuffer(device, transfer.get());

    SDL_GPUCommandBuffer* commands = SDL_AcquireGPUCommandBuffer(device);
    if (commands == nullptr)
    {
        throw std::runtime_error(
            std::format("Cannot acquire a command buffer: {}", SDL_GetError()));
    }
    SDL_GPUCopyPass*                 copy = SDL_BeginGPUCopyPass(commands);
    const SDL_GPUTextureTransferInfo source{.transfer_buffer = transfer.get(),
                                            .offset          = 0,
                                            .pixels_per_row  = data.width,
                                            .rows_per_layer  = data.height};
    const SDL_GPUTextureRegion       destination{
        .texture = texture.get(), .w = data.width, .h = data.height, .d = 1};
    SDL_UploadToGPUTexture(copy, &source, &destination, false);
    SDL_EndGPUCopyPass(copy);
    if (levels > 1)
    {
        SDL_GenerateMipmapsForGPUTexture(commands, texture.get());
    }
    if (!SDL_SubmitGPUCommandBuffer(commands))
    {
        throw std::runtime_error(std::format("Cannot submit an upload: {}", SDL_GetError()));
    }
    return texture;
}

GpuTexture createSolidTexture(SDL_GPUDevice* device, SDL_GPUTextureFormat format,
                              std::span<const std::byte> pixel)
{
    return createTexture(
        device, {.width = 1, .height = 1, .format = format, .pixels = pixel, .mipmaps = false});
}

GpuSampler createMapSampler(SDL_GPUDevice* device)
{
    const SDL_GPUSamplerCreateInfo info{
        .min_filter        = SDL_GPU_FILTER_LINEAR,
        .mag_filter        = SDL_GPU_FILTER_LINEAR,
        .mipmap_mode       = SDL_GPU_SAMPLERMIPMAPMODE_LINEAR,
        .address_mode_u    = SDL_GPU_SAMPLERADDRESSMODE_REPEAT,
        .address_mode_v    = SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE,
        .address_mode_w    = SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE,
        .max_anisotropy    = 8.0F,
        .max_lod           = 1000.0F,
        .enable_anisotropy = true,
    };
    GpuSampler sampler(device, SDL_CreateGPUSampler(device, &info));
    if (!sampler.valid())
    {
        throw std::runtime_error(std::format("Cannot create a sampler: {}", SDL_GetError()));
    }
    return sampler;
}

}  // namespace StarshipSimulator
